to: 4.15.26
from: ^4[.](14[.]([12]?[0-9]|3[0-3])|15[.]([1]?[0-9]|2[0-4]))[+].*$
url: https://issues.redhat.com/browse/NHE-1171
name: SRIOVFailedToConfigureVF
message: |-
  OCP Versions 4.14.34, 4.15.25, 4.16.7 and ALL subsequent versions include kernel datastructure changes which are not compatible with older versions of the SR-IOV operator. Please update SR-IOV operator to versions dated 20240826 or newer before updating OCP.
matchingRules:
- type: PromQL
  promql:
    promql: |
      group(csv_succeeded{_id="", name=~"sriov-network-operator[.].*"})
      or
      0 * group(csv_count{_id=""})
