[package]
name = "cincinnati-graph-data"
version = "0.1.0"
authors = ["Vadim Rutkovsky <vrutkovs@redhat.com>"]
edition = "2018"

[dependencies]
cincinnati = { git = "https://github.com/openshift/cincinnati", rev = "942743910e6fdee387dce99e243dcc52b5cf70bd"}
tokio = { version = "0.2.11", features = [ "fs", "stream" ] }
serde = "^1.0.124"
serde_yaml = "^0.8.11"
anyhow = "1.0"
regex = "^1.1.0"
semver = { version = "^0.9.0", features = [ "serde" ] }
toml = "^0.5.8"
protoc = "=2.8.0"
protobuf = "=2.8.0"
lazy_static = "^1.2.0"
url = "^2.2.1"
reqwest = { version = "^0.10", features = ["gzip"] }
futures = "^0.3"
itertools = "^0.10"
